// Code generated by go-swagger; DO NOT EDIT.

package notify

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// NotifySMSOKCode is the HTTP code returned for type NotifySMSOK
const NotifySMSOKCode int = 200

/*
NotifySMSOK OK

swagger:response notifySMSOK
*/
type NotifySMSOK struct {
}

// NewNotifySMSOK creates NotifySMSOK with default headers values
func NewNotifySMSOK() *NotifySMSOK {

	return &NotifySMSOK{}
}

// WriteResponse to the client
func (o *NotifySMSOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// NotifySMSBadRequestCode is the HTTP code returned for type NotifySMSBadRequest
const NotifySMSBadRequestCode int = 400

/*
NotifySMSBadRequest Ошибка во входных параметрах

swagger:response notifySMSBadRequest
*/
type NotifySMSBadRequest struct {
}

// NewNotifySMSBadRequest creates NotifySMSBadRequest with default headers values
func NewNotifySMSBadRequest() *NotifySMSBadRequest {

	return &NotifySMSBadRequest{}
}

// WriteResponse to the client
func (o *NotifySMSBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// NotifySMSInternalServerErrorCode is the HTTP code returned for type NotifySMSInternalServerError
const NotifySMSInternalServerErrorCode int = 500

/*
NotifySMSInternalServerError Ошибка на стороне сервера

swagger:response notifySMSInternalServerError
*/
type NotifySMSInternalServerError struct {
}

// NewNotifySMSInternalServerError creates NotifySMSInternalServerError with default headers values
func NewNotifySMSInternalServerError() *NotifySMSInternalServerError {

	return &NotifySMSInternalServerError{}
}

// WriteResponse to the client
func (o *NotifySMSInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
