// Code generated by go-swagger; DO NOT EDIT.

package notify

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/RacoonMediaServer/rms-post/internal/server/models"
)

// NotifyEmailHandlerFunc turns a function with the right signature into a notify email handler
type NotifyEmailHandlerFunc func(NotifyEmailParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn NotifyEmailHandlerFunc) Handle(params NotifyEmailParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// NotifyEmailHandler interface for that can handle valid notify email params
type NotifyEmailHandler interface {
	Handle(NotifyEmailParams, *models.Principal) middleware.Responder
}

// NewNotifyEmail creates a new http.Handler for the notify email operation
func NewNotifyEmail(ctx *middleware.Context, handler NotifyEmailHandler) *NotifyEmail {
	return &NotifyEmail{Context: ctx, Handler: handler}
}

/*
	NotifyEmail swagger:route POST /notify/email notify notifyEmail

Отправить E-Mail
*/
type NotifyEmail struct {
	Context *middleware.Context
	Handler NotifyEmailHandler
}

func (o *NotifyEmail) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewNotifyEmailParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
