// Code generated by go-swagger; DO NOT EDIT.

package notify

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/RacoonMediaServer/rms-post/internal/server/models"
)

// NotifySMSHandlerFunc turns a function with the right signature into a notify s m s handler
type NotifySMSHandlerFunc func(NotifySMSParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn NotifySMSHandlerFunc) Handle(params NotifySMSParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// NotifySMSHandler interface for that can handle valid notify s m s params
type NotifySMSHandler interface {
	Handle(NotifySMSParams, *models.Principal) middleware.Responder
}

// NewNotifySMS creates a new http.Handler for the notify s m s operation
func NewNotifySMS(ctx *middleware.Context, handler NotifySMSHandler) *NotifySMS {
	return &NotifySMS{Context: ctx, Handler: handler}
}

/*
	NotifySMS swagger:route POST /notify/sms notify notifySMS

Отправить уведомление по SMS
*/
type NotifySMS struct {
	Context *middleware.Context
	Handler NotifySMSHandler
}

func (o *NotifySMS) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewNotifySMSParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
