// Code generated by go-swagger; DO NOT EDIT.

package notify

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new notify API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for notify API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	NotifyEmail(params *NotifyEmailParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*NotifyEmailOK, error)

	NotifySMS(params *NotifySMSParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*NotifySMSOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
NotifyEmail отправитьs e mail
*/
func (a *Client) NotifyEmail(params *NotifyEmailParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*NotifyEmailOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewNotifyEmailParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "notifyEmail",
		Method:             "POST",
		PathPattern:        "/notify/email",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"multipart/form-data"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &NotifyEmailReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*NotifyEmailOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for notifyEmail: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
NotifySMS отправитьs уведомление по s m s
*/
func (a *Client) NotifySMS(params *NotifySMSParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*NotifySMSOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewNotifySMSParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "notifySMS",
		Method:             "POST",
		PathPattern:        "/notify/sms",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"multipart/form-data"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &NotifySMSReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*NotifySMSOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for notifySMS: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
