// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Post API
//
//	Post API for Racoon Media Server Project
//	Schemes:
//	  http
//	Host: 136.244.108.126
//	BasePath: /
//	Version: 1.0.0
//
//	Consumes:
//	  - multipart/form-data
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
