// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "multipart/form-data"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Post API for Racoon Media Server Project",
    "title": "Post API",
    "version": "1.0.0"
  },
  "host": "136.244.108.126",
  "paths": {
    "/notify/email": {
      "post": {
        "security": [
          {
            "key": []
          }
        ],
        "tags": [
          "notify"
        ],
        "summary": "Отправить E-Mail",
        "operationId": "notifyEmail",
        "parameters": [
          {
            "type": "string",
            "description": "Адрес получателя",
            "name": "to",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "description": "Тема сообщения",
            "name": "subject",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "name": "text",
            "in": "formData",
            "required": true
          },
          {
            "type": "file",
            "name": "attachment",
            "in": "formData"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Ошибка во входных параметрах"
          },
          "500": {
            "description": "Ошибка на стороне сервера"
          }
        }
      }
    },
    "/notify/sms": {
      "post": {
        "security": [
          {
            "key": []
          }
        ],
        "tags": [
          "notify"
        ],
        "summary": "Отправить уведомление по SMS",
        "operationId": "notifySMS",
        "parameters": [
          {
            "maxLength": 60,
            "minLength": 2,
            "type": "string",
            "description": "Текст сообщения",
            "name": "text",
            "in": "formData",
            "required": true
          },
          {
            "maxLength": 12,
            "type": "string",
            "description": "Телефон получателя",
            "name": "to",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Ошибка во входных параметрах"
          },
          "500": {
            "description": "Ошибка на стороне сервера"
          }
        }
      }
    }
  },
  "definitions": {
    "principal": {
      "type": "object",
      "properties": {
        "token": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "key": {
      "type": "apiKey",
      "name": "x-token",
      "in": "header"
    }
  },
  "tags": [
    {
      "description": "Рассылка уведомлений",
      "name": "notify"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "multipart/form-data"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Post API for Racoon Media Server Project",
    "title": "Post API",
    "version": "1.0.0"
  },
  "host": "136.244.108.126",
  "paths": {
    "/notify/email": {
      "post": {
        "security": [
          {
            "key": []
          }
        ],
        "tags": [
          "notify"
        ],
        "summary": "Отправить E-Mail",
        "operationId": "notifyEmail",
        "parameters": [
          {
            "type": "string",
            "description": "Адрес получателя",
            "name": "to",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "description": "Тема сообщения",
            "name": "subject",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "name": "text",
            "in": "formData",
            "required": true
          },
          {
            "type": "file",
            "name": "attachment",
            "in": "formData"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Ошибка во входных параметрах"
          },
          "500": {
            "description": "Ошибка на стороне сервера"
          }
        }
      }
    },
    "/notify/sms": {
      "post": {
        "security": [
          {
            "key": []
          }
        ],
        "tags": [
          "notify"
        ],
        "summary": "Отправить уведомление по SMS",
        "operationId": "notifySMS",
        "parameters": [
          {
            "maxLength": 60,
            "minLength": 2,
            "type": "string",
            "description": "Текст сообщения",
            "name": "text",
            "in": "formData",
            "required": true
          },
          {
            "maxLength": 12,
            "type": "string",
            "description": "Телефон получателя",
            "name": "to",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Ошибка во входных параметрах"
          },
          "500": {
            "description": "Ошибка на стороне сервера"
          }
        }
      }
    }
  },
  "definitions": {
    "principal": {
      "type": "object",
      "properties": {
        "token": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "key": {
      "type": "apiKey",
      "name": "x-token",
      "in": "header"
    }
  },
  "tags": [
    {
      "description": "Рассылка уведомлений",
      "name": "notify"
    }
  ]
}`))
}
